### ISSUE TITLE
Wrong redirect if browser refreshed during recovery setup

### ISSUE THREAD

**Issue by vgrichina** [nearprotocol/near-wallet#276] opened 2019-12-11 08:49 UTC
**Problem**

If browser is refreshed during recovery setup, user is redirected to the point of refresh after completing setup.

**Expected Behavior**

User is redirected to dashboard or the app initiating login flow.

**Steps to reproduce**

1. Create new account.
2. Refresh browser page on "Protect your Account"
3. Select "I choose to backup my account manually" and complete the flow.

**NOTE**

Issue might be more generic than that, I didn't test refreshing on other pages.

**Comment by kcole16** [comment] 2019-12-11 18:03
I don't think we're persisting the redirect URL, so anytime a user refreshes, the new redirect URL is set (which in this case is ```/set-recovery```). 

Seems like the best way to do this is to set the ```redirect_url``` during the ```PrivateRoute``` redirect, as this is the only time the user's flow will be interrupted by account creation.

**Comment by marcinbodnar** [comment] 2019-12-11 19:32
Yes, it's a more generic problem. One thing is that we set redirect_url on every page refresh, but the main problem is that redux state is cleared on every page reload so we are not able to reproduce redirect_url after a page refresh. 

We can use redux middleware like `redux-storage` or `redux-persist` to reproduce state from before refresh, and additionally make sure that in this case redirect_url will not be set again (in Routing.js).

Want me to implement this solution?

**Comment by vgrichina** [comment] 2019-12-12 10:16
@marcinbodnar yes, I think it's good idea to use it, as long as we can control what is persisted. For now let's limit to redirect-related stuff.

**Comment by kcole16** [comment] 2020-02-24 01:36
Closed by #291

**Closed by kcole16** 2020-02-24 01:36 UTC
